#!/bin/sh

# Interactive shell

case $- in
  *i*) ;;
  *) return 
esac


# VI Control Keys

set -o vi

# Aliases
alias config='cd ~/repos/gitlab/itbarsoum/dotfiles'
alias codeviolin='cd ~/repos/projects/codeviolin'
alias fewproject='cd ~/repos/projects/fewproject'
alias private='cd ~/repos/gitlab/itbarsoum/private'
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias preview='browser-sync start --server --files "*.html, css/*.css"'
alias globaldir='cd ~/repos/global'
alias list='ls ~/repos/gitlab/itbarsoum/dotfiles/scripts'


# Functions

push() {
  git add .
  git commit
  git push
  alert
}



# History

HISTCONTROL=ignoreboth
HISTFILESIZE=30

# Optics


rgb () {
  echo -n $'\033[38;2;'$1';'$2';'$3'm'
} && export -f rgb

rgbg () {
  echo -n $'\033[48;2;'$1';'$2';'$3'm'
} && export -f rgb

export PROMPT_COMMAND='
    if [[ $HOME == $PWD ]]; then
    export PROMPTDIR="[~/]"
  elif [[ $HOME == ${PWD%/*} ]]; then
    export PROMPTDIR="[${PWD##*/}]"
  elif [[ / == $PWD ]]; then
    export PROMPTDIR="[/]"
  elif [[ "" == ${PWD%/*} ]]; then
    export PROMPTDIR=$PWD
  else
    # TODO fixeme with ascii char
    export PROMPTDIR=[/${PWD##*/}]
  fi
  if [[ $EUID == 0 ]]; then
    PS1="\[$blinkon$promptbg$red\]\u\[$base03$blinkoff\]@\[\$prompthostc\]\h \[$base03\]\[$promptdirc\]"$PROMPTDIR" \[$reset$promptglyphc\]$promptglyph \[$reset\]"
  else 
    PS1="\[$base03\]\[$promptdirc\]"$PROMPTDIR" \[$reset$twitch\]$promptglyph \[$reset\]"
 fi
'

# Paths
export PATH=~/repos/gitlab/itbarsoum/dotfiles/scripts/:$PATH
export PATH=~/repos/gitlab/itbarsoum/private/bash/now/:$PATH
export PATH="/home/itbarsoum99/repos/gitlab/itbarsoum/dotfiles/lynx:/home/itbarsoum99/repos/gitlab/itbarsoum/private/bash/now/:/home/itbarsoum99/repos/gitlab/itbarsoum/dotfiles/scripts/:/home/itbarsoum99/bin:/usr/local/bin:/usr/bin:/bin":$PATH
